import os
import sys
from dotenv import load_dotenv
load_dotenv()

class BotConfig:
    def __init__(self, app_id_env, app_password_env):
        self.APP_ID = os.environ.get(app_id_env, "")
        self.APP_PASSWORD = os.environ.get(app_password_env, "")
        print(f"APP_ID: {self.APP_ID}", file=sys.stderr)
        print(f"APP_PASSWORD: {self.APP_PASSWORD}", file=sys.stderr)

MASERVICES_BOT_CONFIG = BotConfig("MASERVICES_MICROSOFT_APP_ID", "MASERVICES_MICROSOFT_APP_PASSWORD")
TENDERED_BOT_CONFIG = BotConfig("TENDERED_MICROSOFT_APP_ID", "TENDERED_MICROSOFT_APP_PASSWORD")
JLLSERVICES_BOT_CONFIG = BotConfig("JLLSERVICES_MICROSOFT_APP_ID", "JLLSERVICES_MICROSOFT_APP_PASSWORD")
SERVICEFM_BOT_CONFIG = BotConfig("SERVICEFM_MICROSOFT_APP_ID", "SERVICEFM_MICROSOFT_APP_PASSWORD")
DOWNER_BOT_CONFIG = BotConfig("DOWNER_MICROSOFT_APP_ID", "DOWNER_MICROSOFT_APP_PASSWORD")
INSURGENCE_BOT_CONFIG = BotConfig("INSURGENCE_MICROSOFT_APP_ID", "INSURGENCE_MICROSOFT_APP_PASSWORD")
SALESRESEARCH_BOT_CONFIG = BotConfig("SALESRESEARCH_MICROSOFT_APP_ID", "SALESRESEARCH_MICROSOFT_APP_PASSWORD")